const ADMIN_EMAIL = "admin@gmail.com";
const ADMIN_PASSWORD = "admin@123";

const USERS = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    phoneNumber: "1234567890",
    password: "Password1",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "janesmith@example.com",
    phoneNumber: "9876543210",
    password: "Password2",
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice@example.com",
    phoneNumber: "5551234567",
    password: "Password3",
  },
  {
    firstName: "Bob",
    lastName: "Brown",
    email: "bob@example.com",
    phoneNumber: "5559876543",
    password: "Password4",
  },
  {
    firstName: "Eva",
    lastName: "Williams",
    email: "eva@example.com",
    phoneNumber: "7771122334",
    password: "Password5",
  },
  {
    firstName: "Mike",
    lastName: "Johnson",
    email: "mike@example.com",
    phoneNumber: "5553344556",
    password: "Password6",
  },
  {
    firstName: "Sarah",
    lastName: "Davis",
    email: "sarah@example.com",
    phoneNumber: "7774455667",
    password: "Password7",
  },
  {
    firstName: "David",
    lastName: "Robinson",
    email: "david@example.com",
    phoneNumber: "5555566677",
    password: "Password8",
  },
  {
    firstName: "Olivia",
    lastName: "Martinez",
    email: "olivia@example.com",
    phoneNumber: "3338899000",
    password: "Password9",
  },
  {
    firstName: "Daniel",
    lastName: "Garcia",
    email: "daniel@example.com",
    phoneNumber: "4441122334",
    password: "Password10",
  },
  {
    firstName: "Sophia",
    lastName: "Smith",
    email: "sophia@example.com",
    phoneNumber: "1231111111",
    password: "Password11",
  },
  {
    firstName: "Mason",
    lastName: "Johnson",
    email: "mason@example.com",
    phoneNumber: "1232222222",
    password: "Password12",
  },
  {
    firstName: "Emma",
    lastName: "Williams",
    email: "emma@example.com",
    phoneNumber: "1233333333",
    password: "Password13",
  },
  {
    firstName: "Liam",
    lastName: "Brown",
    email: "liam@example.com",
    phoneNumber: "1234444444",
    password: "Password14",
  },
  {
    firstName: "Olivia",
    lastName: "Jones",
    email: "olivia@example.com",
    phoneNumber: "1235555555",
    password: "Password15",
  },
  {
    firstName: "Noah",
    lastName: "Garcia",
    email: "noah@example.com",
    phoneNumber: "1236666666",
    password: "Password16",
  },
  {
    firstName: "Ava",
    lastName: "Smith",
    email: "ava@example.com",
    phoneNumber: "1237777777",
    password: "Password17",
  },
  {
    firstName: "Ethan",
    lastName: "Martinez",
    email: "ethan@example.com",
    phoneNumber: "1238888888",
    password: "Password18",
  },
  {
    firstName: "Isabella",
    lastName: "Davis",
    email: "isabella@example.com",
    phoneNumber: "1239999999",
    password: "Password19",
  },
  {
    firstName: "Logan",
    lastName: "Taylor",
    email: "logan@example.com",
    phoneNumber: "1111111111",
    password: "Password20",
  },
  {
    firstName: "Lucas",
    lastName: "Johnson",
    email: "lucas@example.com",
    phoneNumber: "1112222222",
    password: "Password21",
  },
  {
    firstName: "Harper",
    lastName: "White",
    email: "harper@example.com",
    phoneNumber: "1113333333",
    password: "Password22",
  },
  {
    firstName: "Layla",
    lastName: "Brown",
    email: "layla@example.com",
    phoneNumber: "1114444444",
    password: "Password23",
  },
  {
    firstName: "Henry",
    lastName: "Smith",
    email: "henry@example.com",
    phoneNumber: "1115555555",
    password: "Password24",
  },
  {
    firstName: "Ella",
    lastName: "Davis",
    email: "ella@example.com",
    phoneNumber: "1116666666",
    password: "Password25",
  },
  {
    firstName: "Benjamin",
    lastName: "Smith",
    email: "benjamin@example.com",
    phoneNumber: "1117777777",
    password: "Password26",
  },
  {
    firstName: "Avery",
    lastName: "White",
    email: "avery@example.com",
    phoneNumber: "1118888888",
    password: "Password27",
  },
  {
    firstName: "Matthew",
    lastName: "Brown",
    email: "matthew@example.com",
    phoneNumber: "1119999999",
    password: "Password28",
  },
  {
    firstName: "Aubrey",
    lastName: "Johnson",
    email: "aubrey@example.com",
    phoneNumber: "2221111111",
    password: "Password29",
  },
  {
    firstName: "Chloe",
    lastName: "Martinez",
    email: "chloe@example.com",
    phoneNumber: "2222222222",
    password: "Password30",
  },
  {
    firstName: "Zoey",
    lastName: "Smith",
    email: "zoe@example.com",
    phoneNumber: "2223333333",
    password: "Password31",
  },
  {
    firstName: "Joseph",
    lastName: "Davis",
    email: "joseph@example.com",
    phoneNumber: "2224444444",
    password: "Password32",
  },
  {
    firstName: "Grace",
    lastName: "White",
    email: "grace@example.com",
    phoneNumber: "2225555555",
    password: "Password33",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael@example.com",
    phoneNumber: "2226666666",
    password: "Password34",
  },
  {
    firstName: "Lily",
    lastName: "Smith",
    email: "lily@example.com",
    phoneNumber: "2227777777",
    password: "Password35",
  },
  {
    firstName: "Jack",
    lastName: "Brown",
    email: "jack@example.com",
    phoneNumber: "2228888888",
    password: "Password36",
  },
  {
    firstName: "Mia",
    lastName: "Martinez",
    email: "mia@example.com",
    phoneNumber: "2229999999",
    password: "Password37",
  },
  {
    firstName: "William",
    lastName: "Taylor",
    email: "william@example.com",
    phoneNumber: "3331111111",
    password: "Password38",
  },
  {
    firstName: "Amelia",
    lastName: "Smith",
    email: "amelia@example.com",
    phoneNumber: "3332222222",
    password: "Password39",
  },
  {
    firstName: "Samuel",
    lastName: "Johnson",
    email: "samuel@example.com",
    phoneNumber: "3333333333",
    password: "Password40",
  },
  {
    firstName: "Nora",
    lastName: "Davis",
    email: "nora@example.com",
    phoneNumber: "3334444444",
    password: "Password41",
  },
  {
    firstName: "James",
    lastName: "Brown",
    email: "james@example.com",
    phoneNumber: "3335555555",
    password: "Password42",
  },
  {
    firstName: "Evelyn",
    lastName: "Smith",
    email: "evelyn@example.com",
    phoneNumber: "3336666666",
    password: "Password43",
  },
  {
    firstName: "Daniel",
    lastName: "Johnson",
    email: "daniel@example.com",
    phoneNumber: "3337777777",
    password: "Password44",
  },
  {
    firstName: "Madison",
    lastName: "White",
    email: "madison@example.com",
    phoneNumber: "3338888888",
    password: "Password45",
  },
  {
    firstName: "John",
    lastName: "Davis",
    email: "john@example.com",
    phoneNumber: "3339999999",
    password: "Password46",
  },
  {
    firstName: "Benjamin",
    lastName: "Taylor",
    email: "benjamin@example.com",
    phoneNumber: "4441111111",
    password: "Password47",
  },
  {
    firstName: "Sofia",
    lastName: "Smith",
    email: "sofia@example.com",
    phoneNumber: "4442222222",
    password: "Password48",
  },
  {
    firstName: "Luke",
    lastName: "Johnson",
    email: "luke@example.com",
    phoneNumber: "4443333333",
    password: "Password49",
  },
  {
    firstName: "Zoe",
    lastName: "Brown",
    email: "zoe@example.com",
    phoneNumber: "4444444444",
    password: "Password50",
  },
  {
    firstName: "Ella",
    lastName: "Jones",
    email: "ella@example.com",
    phoneNumber: "5556667777",
    password: "Password51",
  },
  {
    firstName: "Daniel",
    lastName: "Garcia",
    email: "daniel@example.com",
    phoneNumber: "5557778888",
    password: "Password52",
  },
  {
    firstName: "Mila",
    lastName: "Smith",
    email: "mila@example.com",
    phoneNumber: "5558889999",
    password: "Password53",
  },
  {
    firstName: "David",
    lastName: "Davis",
    email: "david@example.com",
    phoneNumber: "5551110000",
    password: "Password54",
  },
  {
    firstName: "Emily",
    lastName: "Johnson",
    email: "emily@example.com",
    phoneNumber: "6662223333",
    password: "Password55",
  },
  {
    firstName: "Henry",
    lastName: "Martinez",
    email: "henry@example.com",
    phoneNumber: "6663334444",
    password: "Password56",
  },
  {
    firstName: "Harper",
    lastName: "Smith",
    email: "harper@example.com",
    phoneNumber: "6664445555",
    password: "Password57",
  },
  {
    firstName: "Michael",
    lastName: "Taylor",
    email: "michael@example.com",
    phoneNumber: "6665556666",
    password: "Password58",
  },
  {
    firstName: "Scarlett",
    lastName: "Brown",
    email: "scarlett@example.com",
    phoneNumber: "6666667777",
    password: "Password59",
  },
  {
    firstName: "William",
    lastName: "Jones",
    email: "william@example.com",
    phoneNumber: "6667778888",
    password: "Password60",
  },
  {
    firstName: "Grace",
    lastName: "Davis",
    email: "grace@example.com",
    phoneNumber: "6668889999",
    password: "Password61",
  },
  {
    firstName: "Samuel",
    lastName: "Smith",
    email: "samuel@example.com",
    phoneNumber: "7771112222",
    password: "Password62",
  },
  {
    firstName: "Nora",
    lastName: "Martinez",
    email: "nora@example.com",
    phoneNumber: "7772223333",
    password: "Password63",
  },
  {
    firstName: "James",
    lastName: "Brown",
    email: "james@example.com",
    phoneNumber: "7773334444",
    password: "Password64",
  },
  {
    firstName: "Evelyn",
    lastName: "Smith",
    email: "evelyn@example.com",
    phoneNumber: "7774445555",
    password: "Password65",
  },
  {
    firstName: "Benjamin",
    lastName: "Jones",
    email: "benjamin@example.com",
    phoneNumber: "7775556666",
    password: "Password66",
  },
  {
    firstName: "Avery",
    lastName: "Davis",
    email: "avery@example.com",
    phoneNumber: "7776667777",
    password: "Password67",
  },
  {
    firstName: "Logan",
    lastName: "Johnson",
    email: "logan@example.com",
    phoneNumber: "7777778888",
    password: "Password68",
  },
  {
    firstName: "Matthew",
    lastName: "Smith",
    email: "matthew@example.com",
    phoneNumber: "7778889999",
    password: "Password69",
  },
  {
    firstName: "Lily",
    lastName: "Taylor",
    email: "lily@example.com",
    phoneNumber: "8881112222",
    password: "Password70",
  },
  {
    firstName: "Chloe",
    lastName: "Martinez",
    email: "chloe@example.com",
    phoneNumber: "8882223333",
    password: "Password71",
  },
  {
    firstName: "Zoey",
    lastName: "Smith",
    email: "zoe@example.com",
    phoneNumber: "8883334444",
    password: "Password72",
  },
  {
    firstName: "Joseph",
    lastName: "Davis",
    email: "joseph@example.com",
    phoneNumber: "8884445555",
    password: "Password73",
  },
  {
    firstName: "Madison",
    lastName: "Jones",
    email: "madison@example.com",
    phoneNumber: "8885556666",
    password: "Password74",
  },
  {
    firstName: "John",
    lastName: "Brown",
    email: "john@example.com",
    phoneNumber: "8886667777",
    password: "Password75",
  },
  {
    firstName: "Benjamin",
    lastName: "Martinez",
    email: "benjamin@example.com",
    phoneNumber: "9991112222",
    password: "Password76",
  },
  {
    firstName: "Sofia",
    lastName: "Taylor",
    email: "sofia@example.com",
    phoneNumber: "9992223333",
    password: "Password77",
  },
  {
    firstName: "Luke",
    lastName: "Johnson",
    email: "luke@example.com",
    phoneNumber: "9993334444",
    password: "Password78",
  },
  {
    firstName: "Zoe",
    lastName: "Davis",
    email: "zoe@example.com",
    phoneNumber: "9994445555",
    password: "Password79",
  },
  {
    firstName: "Ethan",
    lastName: "Johnson",
    email: "ethan@example.com",
    phoneNumber: "9995556666",
    password: "Password80",
  },
];

module.exports = { ADMIN_EMAIL, ADMIN_PASSWORD, USERS };
